openapi: 3.2.0
info:
  title: Solera Dashboard Assignment Estimate Return API
  description: ''
  contact:
    name: Solera
    url: http://www.audatex.us/product.asp?pageid=zContact_us
  license:
    name: '@SoleraNorth America, Inc. All rights reserved'
    url: http://www.audatex.us/
  version: '2.0'
servers:
- url: /TestAssignmentapi
security:
- oauth2:
  - readAccess
  - writeAccess
tags:
- name: EstimateReturn
paths:
  /api/v2/EstimateReturnResponse:
    post:
      tags:
      - EstimateReturn
      summary: Generate EstimateReturn Response
      responses:
        '200':
          description: Success
      operationId: postApiV2EstimateReturnResponse
      x-operation-id-source: derived
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: Authorization using the JWT Bearer scheme
      flows:
        password:
          tokenUrl: https://dispatch-login-demo.audatex.com/connect/token
          scopes:
            b2b.fnol.api: Audatex Assignment API Access
